ta = int(input('The order for table: '))
dtem1 = input('Dish item: ')
hm1 = int(input('How many: '))
dtem2 = input('Dish item: ')
hm2 = int(input('How many: '))
dtem3 = input('Dish item: ')
hm3 = int(input('How many: '))
print("\n=================================")
print(f"Order for Table {ta}")
print(f"* {dtem1} : {hm1}")
print(f"* {dtem2} : {hm2}")
print(f"* {dtem3} : {hm3}")
print("Total items :",hm1+hm2+hm3)