ncus = int(input('Number of customers: '))
me1, ma1, cal1 = input('Enter food, amount, cal: ').split()
me2, ma2, cal2 = input('Enter food, amount, cal: ').split()
me3, ma3, cal3 = input('Enter food, amount, cal: ').split()
print("---- Meal summary ----")
print(f"{me1} x {ma1}\t{int(cal1)*int(ma1)}")
print(f"{me2} x {ma2}\t{int(cal2)*int(ma2)}")
print(f"{me3} x {ma3}\t{int(cal3)*int(ma3)}")
print(f"Soup and sauce x {ncus}\t {100*ncus}")
print(f"Total calories for all is {int(cal1)*int(ma1)+int(cal2)*int(ma2)+int(cal3)*int(ma3)+100*ncus:.2f} kCal.")
print(f"Avg calories for each person is {(int(cal1)*int(ma1)+int(cal2)*int(ma2)+int(cal3)*int(ma3)+100*ncus)/5:.2f} kCal.")